### ISSUE TITLE
Persistent role inclusion failure 

### ISSUE THREAD

**Issue by piroux** [RebelCodeBase/testaid#6] opened 2019-08-22 17:49 UTC
## Summary
I have been bitten by a weird bug of testaid, which might be related to how testaid, Ansible or Molecule load the files. Or maybe it is related to some cache.
I have to admit I cannot really understand why the bug is triggered but I know how to trigger it.

## Bug reproduction
Indeed, I can reproduce it with the following instructions:

- clone the testaid repo and enter the new directory
- create a virtualenv and install requirements
```
testaid $ pipenv install --three -r test-requirements.txt
testaid $ pipenv shell
```

- go to the `test/system/debian/roles` directory
```
testaid $ cd test/system/debian/roles
```

- go to the `anarchism` role and run `molecule test` -> it will SUCCEED
```
roles $ cd anarchism
anarchism $ molecule test
```

- go back to the `test/system/debian/roles` directory
```
anarchism $ cd ..
```

- create a very simple new role `simplism`
```
roles $ mkdir -p simplism/tasks
roles $ cat <<EOF > simplism/tasks/main.yml
---

- name: main | simple dummy task
  debug:
    msg: "I am quite simple and always succeed"
EOF
```

- create a simple new role `roleinclusion-simple` that will include the `simplism` role
```
roles $ cp -a anarchism roleinclusion-simple
roles $ cat <<EOF >> roleinclusion-simple/tasks/main.yml

- name: (main) dynamic loading of simple role
  include_role:
    name: simplism
    public: false
EOF
roles $ cat <<EOF > roleinclusion-simple/molecule/default/playbook.yml
---
- name: converge
  hosts: all
  gather_facts: true
  roles:
    - roleinclusion-simple
EOF
```

- go to the `roleinclusion-simple` role and run `molecule test` -> it will SUCCEED
```
roles $ cd roleinclusion-simple
roleinclusion-simple $ molecule test
```

Until now, everything has worked accordingly as it was supposed to.
Now the mess begins ;)

- go back to the `test/system/debian/roles` directory
```
roleinclusion-simple $ cd ..
```
- import a more feature complete and more complex role:
```
roles $ ansible-galaxy install -p . newrelic.newrelic-infra
```

- create a simple new role `roleinclusion-complex` that will include the previous complex role
```
roles $ cp -a anarchism roleinclusion-complex
roles $ cat <<EOF >> roleinclusion-complex/tasks/main.yml

- name: (main) import complex role
  include_role:
    name: newrelic.newrelic-infra
    public: false
    apply:
      vars:
        nrinfragent_config:
          license_key: B000000000000000000000000000000000000000
        nrinfragent_os_name: Debian
        nrinfragent_os_codename: buster
EOF
roles $ cat <<EOF > roleinclusion-complex/molecule/default/playbook.yml
---
- name: converge
  hosts: all
  gather_facts: true
  roles:
    - roleinclusion-complex
EOF
```
- go to the `roleinclusion-complex` role and run `molecule test` -> it will FAIL
```
roles $ cd roleinclusion-complex
roleinclusion-complex $ molecule test
```

- go back to the `roleinclusion-simple` role and run `molecule test` -> it will FAIL **although it was passing before !** (see traceback below)
```
roleinclusion-complex $ cd ..
roles $ cd roleinclusion-simple
roleinclusion-simple $ molecule test
```

## Expected Results
We should expect  testaid to support any inclusion of roles, wether they are dynamic (include) or static (import).
Morever, the minimum we can can expect from testaid is that, if it does not support some features of ansible, it should not have any effect on others roles whose tests were previously passing correctly.

## Actual Results 
Now you can try to run `molecule test` in any of the roles of the `test/system/debian/roles` directory, they will now fail.
This is a real deal because it means that testaid was not only _not handling_ the inclusion of another roles, but this failure makes subsequent tests of roles to fail too.
It seems that something (ansible, molecule or testaid ?) keeps some kind of bad state with the first test of a role that was including some other complex roles.

By complex, it could be:
- a role that has specific molecule playbook for the different steps or very customized molecule.yml file.
- or a role that needs the facts (`gather_facts: true`) to be able to run correctly.

I have not dug really into why and which of the previous characteristics matter, I just know that the newrelic role fits enough to make testaid to fail.

Here is one part of the traceback:
```
_ ERROR at setup of test_testaid_system_role_inventory[ansible://molecule-anarchism] _

request = <SubRequest 'testvars' for <Function test_testaid_system_role_packages_installed[ansible://molecule-anarchism]>>
moleculebook = <testaid.moleculebook.MoleculeBook object at 0x7f1cdb7f5780>
jsonvars = <testaid.jsonvars.JsonVars object at 0x7f1cdb794ac8>
resolve_vars = True, gatherfrom_moleculehost = True, gather_facts = True
extra_vars = True
cache_key = 'testvars/home/piroux/.cache/molecule/roleinclusion-simple/default'

    @pytest.fixture(scope='session')
    def testvars(request,
                 moleculebook,
                 jsonvars,
                 resolve_vars,
                 gatherfrom_moleculehost,
                 gather_facts,
                 extra_vars,
                 cache_key):
        '''Expose ansible variables and facts of a molecule test scenario.'''
        testvars = TestVars.get_cache(request, cache_key)
        if testvars is None:
            testvars_object = TestVars(
                     moleculebook,
                     jsonvars,
                     resolve_vars,
                     gatherfrom_moleculehost,
                     gather_facts,
>                    extra_vars)

/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/plugin.py:305:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/testvars.py:47: in __init__
    jsonvars.resolve()
/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/jsonvars.py:59: in resolve
    self._templates.resolve()
/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/templates.py:35: in resolve
    playbook_results = self._moleculebook.run()
/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/moleculebook.py:124: in run
    return self._moleculeplay.run_playbook(self._playbook)
/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/moleculeplay.py:59: in run_playbook
    result = ansiblerun.run(play)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testaid.ansiblerun.AnsibleRun object at 0x7f1cdb79fdd8>
play = ansible playbook

    def run(self, play):
        tqm = None
        rc = ResultCallback()
        try:
            tqm = TaskQueueManager(inventory=self._inventory,
                                   variable_manager=self._variable_manager,
                                   loader=self._loader,
                                   passwords=dict(),
                                   stdout_callback=rc)
            tqm.run(play)
        finally:
            if tqm is not None:
                tqm.cleanup()
            shutil.rmtree(C.DEFAULT_LOCAL_TMP, True)

        if rc.failed_playbook_run:
            raise AnsibleRunError(
                rc.result_playbook_run,
>               'Unable to run playbook. Is your host up?')
E           testaid.exceptions.AnsibleRunError: Unable to run playbook. Is your host up?

/home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/local/lib/python3.6/site-packages/testaid/ansiblerun.py:36: AnsibleRunError
========================= 1 skipped, 3 error in 33.92s =========================
```

It will actually output that traceback for each function test using the `testvars` fixture offered by testaid.

## Recovery from persistent test failures
In order to recover and be able to pass the tests of roles that were previously successful but are not anymore, I have found that the following instructions were helping :
```
roles $ rm -rf newrelic.newrelic-infra
roles $ rm -rf /tmp/molecule ~/.cache/molecule
```

After those, the tests `anarchism` and `roleinclusion-simple` role will pass anew.
If the `newrelic.newrelic-infra` role is installed again, and another `molecule test` is run in `roleinclusion-complex`, the persistent test failures will be back.

## Conclusion
This might sound almost like two separate issues but first lets see if this is reproducible by someone else.

This is really environment related so I am not 100% that it is the fault of testaid directly. But it only appears while using it.

**Comment by RebelCodeBase** [comment] 2019-08-23 00:10
You are absolutely right, the exception handling is horrible and there is no logger. Here is my todo list:
- add Exceptions:
  - TestVarsToJsonError
  - TestVarsFromJsonError
- add Logger
- add API Docs
- [test doc examples](https://sybil.readthedocs.io/en/latest/use.html#pytest)
- add travis CI configuration

I have to find some time to reproduce your bug. And I guess a logger would help a lot.

**Comment by piroux** [comment] 2019-08-23 11:57
Great !!

In order to help you reproduce the bugs, I pushed a branch following the instructions I provided above., so that it is much easier to trigger the bugs.

```
$ git clone --single-branch --branch issue-6-persistent-roleinclusion-failure https://github.com/piroux/testaid testaid_issue_6
$ cd testaid_issue_6
testaid_issue_6 $ pipenv install --three
testaid_issue_6 $ pipenv shell
testaid_issue_6 $ cd test/system/debian/roles
roles $ cd roleinclusion-simple
roleinclusion-simple $ molecule test # will SUCCEED
roleinclusion-simple $ cd ../roleinclusion-complex
roleinclusion-complex $ molecule test # will FAIL
roleinclusion-complex $ cd ../roleinclusion-simple
roleinclusion-simple $ molecule test # will FAIL
```

To recover:
```
roleinclusion-simple $ cd ..
roles $ rm -rf newrelic.newrelic-infra
roles $ rm -rf /tmp/molecule ~/.cache/molecule
```

And it will work again:
```
roles $ cd roleinclusion-simple
roleinclusion-simple $ molecule test # will SUCCEED
```

If we reinstall the newrelic role, the simple one will fail again, without even first trying to test the complex one another time:
```
roleinclusion-simple $ cd ..
roles $ ansible-galaxy install -p . newrelic.newrelic-infra
roles $ cd roleinclusion-simple
roleinclusion-simple $ molecule test # will FAIL
```

**Comment by piroux** [comment] 2019-08-23 16:42
> And I guess a logger would help a lot.

While it is true that more debug logging could output a lot of useful information, it might be easier to just use a remote debugger like [rpdb](https://pypi.org/project/rpdb/) or [irpdb](https://pypi.org/project/ripdb/).

Maybe you already know how to use those tools, but in case you don't, here is the point: with them, you can set some breakpoint anywhere in the code source of ansible, molecule or testaid, and a remote debugger will be opened that you can connect to with telnet/nc.

**Comment by RebelCodeBase** [comment] 2019-08-24 02:08
That‘s very interesting and no, I haven‘t used those debuggers. I will have a look!

Your detailed bug report is very welcome. I will still need to find time to solve this issue as there are some other things I have to do first. But I will dig into this for sure.

**Comment by RebelCodeBase** [comment] 2019-09-10 10:05
I have not yet looked into your code but this issue seems to be related to #7. As testvars has *session scope* and testvars by default includes all roles present in the roles directory, any role can trigger a bug which will affect all other roles.

So I will have a look why your particular example fails (because this is of course a bug that needs to be addressed) but a more general solution would be to add more configurations options and saner defaults to the role inclusion mechanism of testvars. Thus, I will start with #7.

**Comment by RebelCodeBase** [comment] 2019-10-13 21:50
First of all: thanks again for your effort! Sorry that it took so long to have a look at it...

Here are some catches (using testaid 0.12.5):
- I used to think that the default playbook must be called ``converge.yml``. After seeing your examples and reading the molecule documentation more carefully I have changed that to ``playbook.yml``. With this and the new role inclusion feature the roles should be independent and the weird side-effects should be gone. (By the way, I should definitely expand the system tests to include more than one role.)
- Due to the newly added error printing in case of an exception it was quite easy to find the first (of many?) problems: 

```
    E           testaid.exceptions.AnsibleRunError: Unable to run playbook.
    E           Error message: The task includes an option with an undefined variable. The error was: 'nrinfragent_tarball_version' is undefined
```
(I should implement some similar reporting for the conversion step)

Maybe you can have a look again? Please tell me if you think that I should have handled your bug report in a different way. And of course: more bug reports are very welcome!

**Comment by RebelCodeBase** [comment] 2019-11-13 01:10
I close this for now, feel free to reopen.

**Closed by RebelCodeBase** 2019-11-13 01:10 UTC
Labels: bug

**Comment by piroux** [comment] 2019-11-13 14:24
Indeed, the `0.12.5` release fixed some parts of the issue. Still I had to add fix others parts of the `moleculeenv.py` file to make it really work. I will send you a PR next week.
